name: Build
on: [push]
jobs:
  build:
    if: ${{ false }}
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore NuGet Packages
      run: nuget restore "CM Launcher.sln"

    - name: Build CML
      working-directory: ./Windows
      run: |
        dotnet build --configuration Release
        mv "bin/Release/CM Launcher.exe" "bin/Release/CML.exe"

    - uses: actions/upload-artifact@v2
      with:
        name: CML
        path: Windows/bin/Release/CML.exe
  build-osx:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: latest
        xamarin-mac-version: latest
        xcode-version: latest

    - name: Restore NuGet Packages
      run: nuget restore "CM Launcher.sln"

    - name: Build CML
      working-directory: ./OSX
      run: |
        msbuild /property:Configuration=Release

    - uses: papeloto/action-zip@v1
      with:
        files: OSX/bin/Release/CML.app
        dest: CML2.app.zip

    - id: upload-file
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.gcp_credentials }}
        path: CML2.app.zip
        destination: chromapper/CML2.app.zip
