name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.3
       
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
     
    - name: Restore NuGet Packages
      run: nuget restore "CM Launcher.sln"

    - name: Build CML
      working-directory: ./Windows
      run: dotnet build --configuration Release

    - uses: actions/upload-artifact@v2
      with:
        name: CML.exe
        path: Windows/bin/Release/CM Launcher.exe
