name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build CML
      working-directory: ./Windows
      run: |
        dotnet build --configuration Release
        mv "Windows/bin/Release/CM Launcher.exe" CML.exe

    - uses: actions/upload-artifact@v2
      with:
        name: CML
        path: CML.exe
